plugins {
    id 'com.android.application'
}

android {
    namespace 'com.car.autohotspot'
    compileSdk 28

    defaultConfig {
        applicationId "com.car.autohotspot"
        minSdk 21
        // 核心技巧：targetSdk 设为 22，在 Android 9.0 上免动态权限、免 Shizuku
        targetSdk 22
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
