plugins {
    id 'com.android.application'
}

android {
    namespace 'com.car.autohotspot'
    compileSdk 28

    defaultConfig {
        applicationId "com.car.autohotspot"
        minSdk 24
        targetSdk 28
        versionCode 2
        versionName "2.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
